_core:
  default_config_hash: ekC0X_U-NFfSyOOjmF6u906bacV7KfRXgiwBgHkeWls
auth: 1
debug: 0
auth-user: exchange
auth-pass: PzwYDZkkENgrGw
auth-ip: ''
zip: 0
file-path: cml
file-limit: '95000000'
cmlmigrations: 1
langcode: ru
