_core:
  default_config_hash: JRi85rlPwQxy7rBiLloK_Uk4Yug_bUH8jYdK2WxsuaU
langcode: ru
page_alter: false
raw_names: false
error_handlers:
  1: 1
rebuild_theme: false
debug_mail_file_format: '%to-%subject-%datetime.mail.txt'
debug_mail_directory: 'temporary://devel-mails'
devel_dumper: kint
debug_logfile: 'temporary://drupal_debug.txt'
debug_pre: false
