alfa_active: '0'
alfa_test_login: ''
alfa_test_token: ''
alfa_live_login: ''
alfa_live_token: ''
cloudpayments_active: '0'
cloudpayments_publicId: ''
cloudpayments_skin: classic
paykeeper_active: '0'
paykeeper_secure: ''
paykeeper_test_login: ''
paykeeper_test_token: ''
paykeeper_live_login: ''
paykeeper_live_token: ''
robokassa_active: '0'
robokassa_login: ''
robokassa_live_pass: ''
robokassa_live_pass2: ''
robokassa_test_pass: ''
robokassa_test_pass2: ''
robokassa_description: ''
sber_active: '0'
sber_test_login: ''
sber_test_token: ''
sber_live_login: ''
sber_live_token: ''
sbercredit_active: '0'
sbercredit_test_login: ''
sbercredit_test_token: ''
sbercredit_live_login: ''
sbercredit_live_token: ''
sberinstallment_active: '0'
sberinstallment_test_login: ''
sberinstallment_test_token: ''
sberinstallment_live_login: ''
sberinstallment_live_token: ''
sgb_active: '0'
sgb_test_login: ''
sgb_test_token: ''
sgb_live_login: ''
sgb_live_token: ''
tinkoff_active: '0'
tinkoff_test_login: ''
tinkoff_test_token: ''
tinkoff_live_login: ''
tinkoff_live_token: ''
tinkoff_taxation: osn
tinkoff_tax: none
tinkoff_credit_active: '0'
tinkoff_credit_test_login: ''
tinkoff_credit_test_token: ''
tinkoff_credit_live_login: ''
tinkoff_credit_live_token: ''
tinkoff_dolyame_active: '0'
tinkoff_dolyame_test_login: ''
tinkoff_dolyame_test_token: ''
tinkoff_dolyame_live_login: ''
tinkoff_dolyame_live_token: ''
yookassa_active: '1'
yookassa_test_login: '320072'
yookassa_test_token: test_5a_Eag3kuLtn_vTBRbHGnClrRxOpzXO8_8y5q7a-wy4
yookassa_live_login: '312934'
yookassa_live_token: live_5GWYgnoRiIxQMjwEqR0Nr1OdpUwWm0NRqWUcwFJP7yY
